### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by nicruo** [msworkshop2024/github-games-gitdomelo#1]
When attempting to access this at https://msworkshop2024.github.io/github-games-gitdomelo, I am getting a 404. This could be caused by a couple of things:

- GitHub Pages needs to be enabled on the  branch. You can fix this in the repository settings.
- The **index.html** file is incorrectly named **inde.html**. We will fix this together in class.

Can you fix the first bullet, please?

**Comment by gitdomelo** [comment]
Fix version:
https://github.com/msworkshop2024/github-games-gitdomelo/releases/tag/v3
